# Generated by Django 3.2.11 on 2022-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusSta', '0003_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pv',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
