# Generated by Django 3.2.11 on 2022-01-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusSta', '0005_auto_20220122_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(null=True, upload_to='media/', verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(2, '展示'), (1, '隐藏')], default=2, verbose_name='状态'),
        ),
    ]
