# Generated by Django 3.2.11 on 2022-01-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusSta', '0008_auto_20220125_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_pic',
            field=models.ImageField(null=True, upload_to='category_pic/', verbose_name='分类图片'),
        ),
        migrations.AddField(
            model_name='post',
            name='annotation',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='文章注释'),
        ),
        migrations.AlterField(
            model_name='post',
            name='desc',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='简介/摘要/首句'),
        ),
    ]
