# Generated by Django 3.2.11 on 2022-01-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusSta', '0010_alter_post_annotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='地址'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='生日'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=6, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='image',
            field=models.ImageField(default='profile_pic/default.png', upload_to='profile_pic/%Y/%m', verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '隐藏'), (2, '展示')], default=2, verbose_name='状态'),
        ),
    ]
