# Generated by Django 3.2.11 on 2022-01-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rusSta', '0015_alter_sidebar_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='name',
        ),
    ]
