# Generated by Django 3.2.11 on 2022-01-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rusSta', '0019_auto_20220127_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat',
            name='people',
        ),
        migrations.RemoveField(
            model_name='cat',
            name='title',
        ),
        migrations.DeleteModel(
            name='dog',
        ),
        migrations.RenameField(
            model_name='collection',
            old_name='title',
            new_name='passagename',
        ),
        migrations.AlterField(
            model_name='sidebar',
            name='status',
            field=models.PositiveIntegerField(choices=[(1, '隐藏'), (2, '展示')], default=2, verbose_name='状态'),
        ),
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
