# Generated by Django 4.2.1 on 2023-07-01 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rusSta", "0021_auto_20220127_1755"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sidebar",
            name="status",
            field=models.PositiveIntegerField(
                choices=[(1, "隐藏"), (2, "展示")], default=2, verbose_name="状态"
            ),
        ),
    ]
